[project]
name = "ae-pipeline"
authors = [{ name = "Max Weiner", email = "max.weiner@imf.tu-freiberg.de" }]
version = "0.1"
requires-python = ">=3.14"
dependencies = [
  "jupyter",
  "jupytext~=1.19",
  "jupyterlab_myst",
  "pandas>=3.0.5",
  "matplotlib>=3.11.1",
  "soundfile>=0.14.0",
  "numpy>=2.5.3",
  "plotly>=7.0.0",
  "pytask>=0.6.0",
  "sqlalchemy>=2.0.52",
  "pydantic>=2.13.5",
  "pyarrow>=25.0.1",
]
license = "MIT"
readme = "README.md"
keywords = []
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python",
]

[project.urls]
Documentation = "https://github.com/institute-of-metal-forming/ae-pipeline/src/branch/main/README.md"
Issues = "https://github.com/institute-of-metal-forming/ae-pipeline/issues"
Source = "https://github.com/institute-of-metal-forming/ae-pipeline"

[build-system]
requires = ["uv_build~=0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.pyright]
venvPath = ".devenv/state"
venv = "venv"

[tool.ruff]

line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 120

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # Pyflakes
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "I",   # isort
]
ignore = [
  "B006", # mutable data structures in task arguments
  "B008", # function calls in task arguments
  "E501", # long lines (string literals)
  "E741", # ambiguous variable names
]


[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
known-first-party = ["ae_pipeline"]

[tool.pytask.ini_options]
paths = ["ae_pipeline"]
ignore = [".*", "_*"]
